insert into interest (user_id, topic) values (1, 'swimming');
insert into interest (user_id, topic) values (2, 'music');
insert into interest (user_id, topic) values (3, 'movies');
insert into interest (user_id, topic) values (4, 'food');
insert into interest (user_id, topic) values (5, 'science');
insert into interest (user_id, topic) values (6, 'cinema');
insert into interest (user_id, topic) values (7, 'music');
insert into interest (user_id, topic) values (8, 'food');
insert into interest (user_id, topic) values (9, 'music');
insert into interest (user_id, topic) values (10, 'self improvement');
insert into interest (user_id, topic) values (11, 'anime');
insert into interest (user_id, topic) values (12, 'tech');
insert into interest (user_id, topic) values (13, 'football');
insert into interest (user_id, topic) values (14, 'tech');
insert into interest (user_id, topic) values (15, 'food');
insert into interest (user_id, topic) values (16, 'art');
insert into interest (user_id, topic) values (17, 'tech');
insert into interest (user_id, topic) values (18, 'music');
insert into interest (user_id, topic) values (19, 'football');
insert into interest (user_id, topic) values (20, 'science');
insert into interest (user_id, topic) values (21, 'art');
insert into interest (user_id, topic) values (22, 'anime');
insert into interest (user_id, topic) values (23, 'make up');
insert into interest (user_id, topic) values (24, 'tech');
insert into interest (user_id, topic) values (25, 'self improvement');
insert into interest (user_id, topic) values (26, 'food');
insert into interest (user_id, topic) values (27, 'self improvement');
insert into interest (user_id, topic) values (28, 'anime');
insert into interest (user_id, topic) values (29, 'music');
insert into interest (user_id, topic) values (30, 'tech');
insert into interest (user_id, topic) values (31, 'art');
insert into interest (user_id, topic) values (32, 'movies');
insert into interest (user_id, topic) values (33, 'art');
insert into interest (user_id, topic) values (34, 'anime');
insert into interest (user_id, topic) values (35, 'movies');
insert into interest (user_id, topic) values (36, 'anime');
insert into interest (user_id, topic) values (37, 'reading');
insert into interest (user_id, topic) values (38, 'science');
insert into interest (user_id, topic) values (39, 'food');
insert into interest (user_id, topic) values (40, 'reading');
insert into interest (user_id, topic) values (41, 'make up');
insert into interest (user_id, topic) values (42, 'art');
insert into interest (user_id, topic) values (43, 'music');
insert into interest (user_id, topic) values (44, 'science');
insert into interest (user_id, topic) values (45, 'self improvement');
insert into interest (user_id, topic) values (46, 'tech');
insert into interest (user_id, topic) values (47, 'e-games');
insert into interest (user_id, topic) values (48, 'series');
insert into interest (user_id, topic) values (49, 'football');
insert into interest (user_id, topic) values (50, 'football');
insert into interest (user_id, topic) values (51, 'art');
insert into interest (user_id, topic) values (52, 'food');
insert into interest (user_id, topic) values (53, 'science');
insert into interest (user_id, topic) values (54, 'art');
insert into interest (user_id, topic) values (55, 'swimming');
insert into interest (user_id, topic) values (56, 'tech');
insert into interest (user_id, topic) values (57, 'food');
insert into interest (user_id, topic) values (58, 'music');
insert into interest (user_id, topic) values (59, 'tech');
insert into interest (user_id, topic) values (60, 'tech');
insert into interest (user_id, topic) values (61, 'cinema');
insert into interest (user_id, topic) values (62, 'tech');
insert into interest (user_id, topic) values (63, 'self improvement');
insert into interest (user_id, topic) values (64, 'cinema');
insert into interest (user_id, topic) values (65, 'e-games');
insert into interest (user_id, topic) values (66, 'movies');
insert into interest (user_id, topic) values (67, 'anime');
insert into interest (user_id, topic) values (68, 'science');
insert into interest (user_id, topic) values (69, 'science');
insert into interest (user_id, topic) values (70, 'anime');
insert into interest (user_id, topic) values (71, 'football');
insert into interest (user_id, topic) values (72, 'anime');
insert into interest (user_id, topic) values (73, 'food');
insert into interest (user_id, topic) values (74, 'art');
insert into interest (user_id, topic) values (75, 'series');
insert into interest (user_id, topic) values (76, 'football');
insert into interest (user_id, topic) values (77, 'e-games');
insert into interest (user_id, topic) values (78, 'art');
insert into interest (user_id, topic) values (79, 'football');
insert into interest (user_id, topic) values (80, 'music');
insert into interest (user_id, topic) values (81, 'e-games');
insert into interest (user_id, topic) values (82, 'tech');
insert into interest (user_id, topic) values (83, 'cinema');
insert into interest (user_id, topic) values (84, 'music');
insert into interest (user_id, topic) values (85, 'reading');
insert into interest (user_id, topic) values (86, 'swimming');
insert into interest (user_id, topic) values (87, 'swimming');
insert into interest (user_id, topic) values (88, 'swimming');
insert into interest (user_id, topic) values (89, 'self improvement');
insert into interest (user_id, topic) values (90, 'e-games');
insert into interest (user_id, topic) values (91, 'football');
insert into interest (user_id, topic) values (92, 'art');
insert into interest (user_id, topic) values (93, 'movies');
insert into interest (user_id, topic) values (94, 'e-games');
insert into interest (user_id, topic) values (95, 'science');
insert into interest (user_id, topic) values (96, 'series');
insert into interest (user_id, topic) values (97, 'e-games');
insert into interest (user_id, topic) values (98, 'science');
insert into interest (user_id, topic) values (99, 'music');
insert into interest (user_id, topic) values (100, 'science');
insert into interest (user_id, topic) values (101, 'self improvement');
insert into interest (user_id, topic) values (102, 'cinema');
insert into interest (user_id, topic) values (103, 'cinema');
insert into interest (user_id, topic) values (104, 'food');
insert into interest (user_id, topic) values (105, 'art');
insert into interest (user_id, topic) values (106, 'anime');
insert into interest (user_id, topic) values (107, 'movies');
insert into interest (user_id, topic) values (108, 'music');
insert into interest (user_id, topic) values (109, 'reading');
insert into interest (user_id, topic) values (110, 'make up');
insert into interest (user_id, topic) values (111, 'anime');
insert into interest (user_id, topic) values (112, 'anime');
insert into interest (user_id, topic) values (113, 'series');
insert into interest (user_id, topic) values (114, 'cinema');
insert into interest (user_id, topic) values (115, 'e-games');
insert into interest (user_id, topic) values (116, 'food');
insert into interest (user_id, topic) values (117, 'reading');
insert into interest (user_id, topic) values (118, 'self improvement');
insert into interest (user_id, topic) values (119, 'science');
insert into interest (user_id, topic) values (120, 'music');
insert into interest (user_id, topic) values (121, 'self improvement');
insert into interest (user_id, topic) values (122, 'art');
insert into interest (user_id, topic) values (123, 'reading');
insert into interest (user_id, topic) values (124, 'football');
insert into interest (user_id, topic) values (125, 'science');
insert into interest (user_id, topic) values (126, 'football');
insert into interest (user_id, topic) values (127, 'cinema');
insert into interest (user_id, topic) values (128, 'anime');
insert into interest (user_id, topic) values (129, 'series');
insert into interest (user_id, topic) values (130, 'tech');
insert into interest (user_id, topic) values (131, 'movies');
insert into interest (user_id, topic) values (132, 'art');
insert into interest (user_id, topic) values (133, 'art');
insert into interest (user_id, topic) values (134, 'movies');
insert into interest (user_id, topic) values (135, 'football');
insert into interest (user_id, topic) values (136, 'music');
insert into interest (user_id, topic) values (137, 'anime');
insert into interest (user_id, topic) values (138, 'anime');
insert into interest (user_id, topic) values (139, 'anime');
insert into interest (user_id, topic) values (140, 'art');
insert into interest (user_id, topic) values (141, 'music');
insert into interest (user_id, topic) values (142, 'reading');
insert into interest (user_id, topic) values (143, 'art');
insert into interest (user_id, topic) values (144, 'anime');
insert into interest (user_id, topic) values (145, 'food');
insert into interest (user_id, topic) values (146, 'art');
insert into interest (user_id, topic) values (147, 'e-games');
insert into interest (user_id, topic) values (148, 'art');
insert into interest (user_id, topic) values (149, 'science');
insert into interest (user_id, topic) values (150, 'art');
insert into interest (user_id, topic) values (151, 'e-games');
insert into interest (user_id, topic) values (152, 'make up');
insert into interest (user_id, topic) values (153, 'make up');
insert into interest (user_id, topic) values (154, 'anime');
insert into interest (user_id, topic) values (155, 'art');
insert into interest (user_id, topic) values (156, 'movies');
insert into interest (user_id, topic) values (157, 'anime');
insert into interest (user_id, topic) values (158, 'self improvement');
insert into interest (user_id, topic) values (159, 'series');
insert into interest (user_id, topic) values (160, 'anime');
insert into interest (user_id, topic) values (161, 'food');
insert into interest (user_id, topic) values (162, 'anime');
insert into interest (user_id, topic) values (163, 'music');
insert into interest (user_id, topic) values (164, 'swimming');
insert into interest (user_id, topic) values (165, 'art');
insert into interest (user_id, topic) values (166, 'reading');
insert into interest (user_id, topic) values (167, 'art');
insert into interest (user_id, topic) values (168, 'football');
insert into interest (user_id, topic) values (169, 'e-games');
insert into interest (user_id, topic) values (170, 'art');
insert into interest (user_id, topic) values (171, 'food');
insert into interest (user_id, topic) values (172, 'swimming');
insert into interest (user_id, topic) values (173, 'music');
insert into interest (user_id, topic) values (174, 'reading');
insert into interest (user_id, topic) values (175, 'cinema');
insert into interest (user_id, topic) values (176, 'football');
insert into interest (user_id, topic) values (177, 'art');
insert into interest (user_id, topic) values (178, 'movies');
insert into interest (user_id, topic) values (179, 'series');
insert into interest (user_id, topic) values (180, 'science');
insert into interest (user_id, topic) values (181, 'reading');
insert into interest (user_id, topic) values (182, 'e-games');
insert into interest (user_id, topic) values (183, 'food');
insert into interest (user_id, topic) values (184, 'swimming');
insert into interest (user_id, topic) values (185, 'cinema');
insert into interest (user_id, topic) values (186, 'make up');
insert into interest (user_id, topic) values (187, 'food');
insert into interest (user_id, topic) values (188, 'science');
insert into interest (user_id, topic) values (189, 'series');
insert into interest (user_id, topic) values (190, 'music');
insert into interest (user_id, topic) values (191, 'self improvement');
insert into interest (user_id, topic) values (192, 'food');
insert into interest (user_id, topic) values (193, 'football');
insert into interest (user_id, topic) values (194, 'art');
insert into interest (user_id, topic) values (195, 'reading');
insert into interest (user_id, topic) values (196, 'food');
insert into interest (user_id, topic) values (197, 'reading');
insert into interest (user_id, topic) values (198, 'make up');
insert into interest (user_id, topic) values (199, 'cinema');
insert into interest (user_id, topic) values (200, 'movies');
insert into interest (user_id, topic) values (201, 'cinema');
insert into interest (user_id, topic) values (202, 'tech');
insert into interest (user_id, topic) values (203, 'anime');
insert into interest (user_id, topic) values (204, 'cinema');
insert into interest (user_id, topic) values (205, 'food');
insert into interest (user_id, topic) values (206, 'swimming');
insert into interest (user_id, topic) values (207, 'series');
insert into interest (user_id, topic) values (208, 'movies');
insert into interest (user_id, topic) values (209, 'make up');
insert into interest (user_id, topic) values (210, 'reading');
insert into interest (user_id, topic) values (211, 'music');
insert into interest (user_id, topic) values (212, 'anime');
insert into interest (user_id, topic) values (213, 'reading');
insert into interest (user_id, topic) values (214, 'food');
insert into interest (user_id, topic) values (215, 'reading');
insert into interest (user_id, topic) values (216, 'food');
insert into interest (user_id, topic) values (217, 'tech');
insert into interest (user_id, topic) values (218, 'make up');
insert into interest (user_id, topic) values (219, 'cinema');
insert into interest (user_id, topic) values (220, 'science');
insert into interest (user_id, topic) values (221, 'e-games');
insert into interest (user_id, topic) values (222, 'series');
insert into interest (user_id, topic) values (223, 'food');
insert into interest (user_id, topic) values (224, 'tech');
insert into interest (user_id, topic) values (225, 'food');
insert into interest (user_id, topic) values (226, 'make up');
insert into interest (user_id, topic) values (227, 'self improvement');
insert into interest (user_id, topic) values (228, 'tech');
insert into interest (user_id, topic) values (229, 'science');
insert into interest (user_id, topic) values (230, 'tech');
insert into interest (user_id, topic) values (231, 'e-games');
insert into interest (user_id, topic) values (232, 'anime');
insert into interest (user_id, topic) values (233, 'make up');
insert into interest (user_id, topic) values (234, 'e-games');
insert into interest (user_id, topic) values (235, 'tech');
insert into interest (user_id, topic) values (236, 'football');
insert into interest (user_id, topic) values (237, 'music');
insert into interest (user_id, topic) values (238, 'food');
insert into interest (user_id, topic) values (239, 'self improvement');
insert into interest (user_id, topic) values (240, 'art');
insert into interest (user_id, topic) values (241, 'anime');
insert into interest (user_id, topic) values (242, 'movies');
insert into interest (user_id, topic) values (243, 'food');
insert into interest (user_id, topic) values (244, 'tech');
insert into interest (user_id, topic) values (245, 'food');
insert into interest (user_id, topic) values (246, 'food');
insert into interest (user_id, topic) values (247, 'cinema');
insert into interest (user_id, topic) values (248, 'make up');
insert into interest (user_id, topic) values (249, 'music');
insert into interest (user_id, topic) values (250, 'science');
insert into interest (user_id, topic) values (251, 'art');
insert into interest (user_id, topic) values (252, 'make up');
insert into interest (user_id, topic) values (253, 'science');
insert into interest (user_id, topic) values (254, 'movies');
insert into interest (user_id, topic) values (255, 'music');
insert into interest (user_id, topic) values (256, 'anime');
insert into interest (user_id, topic) values (257, 'self improvement');
insert into interest (user_id, topic) values (258, 'cinema');
insert into interest (user_id, topic) values (259, 'football');
insert into interest (user_id, topic) values (260, 'music');
insert into interest (user_id, topic) values (261, 'tech');
insert into interest (user_id, topic) values (262, 'e-games');
insert into interest (user_id, topic) values (263, 'football');
insert into interest (user_id, topic) values (264, 'science');
insert into interest (user_id, topic) values (265, 'science');
insert into interest (user_id, topic) values (266, 'cinema');
insert into interest (user_id, topic) values (267, 'art');
insert into interest (user_id, topic) values (268, 'food');
insert into interest (user_id, topic) values (269, 'tech');
insert into interest (user_id, topic) values (270, 'make up');
insert into interest (user_id, topic) values (271, 'e-games');
insert into interest (user_id, topic) values (272, 'movies');
insert into interest (user_id, topic) values (273, 'food');
insert into interest (user_id, topic) values (274, 'science');
insert into interest (user_id, topic) values (275, 'make up');
insert into interest (user_id, topic) values (276, 'reading');
insert into interest (user_id, topic) values (277, 'self improvement');
insert into interest (user_id, topic) values (278, 'tech');
insert into interest (user_id, topic) values (279, 'series');
insert into interest (user_id, topic) values (280, 'football');
insert into interest (user_id, topic) values (281, 'art');
insert into interest (user_id, topic) values (282, 'self improvement');
insert into interest (user_id, topic) values (283, 'anime');
insert into interest (user_id, topic) values (284, 'tech');
insert into interest (user_id, topic) values (285, 'reading');
insert into interest (user_id, topic) values (286, 'series');
insert into interest (user_id, topic) values (287, 'tech');
insert into interest (user_id, topic) values (288, 'football');
insert into interest (user_id, topic) values (289, 'movies');
insert into interest (user_id, topic) values (290, 'music');
insert into interest (user_id, topic) values (291, 'anime');
insert into interest (user_id, topic) values (292, 'cinema');
insert into interest (user_id, topic) values (293, 'cinema');
insert into interest (user_id, topic) values (294, 'series');
insert into interest (user_id, topic) values (295, 'movies');
insert into interest (user_id, topic) values (296, 'anime');
insert into interest (user_id, topic) values (297, 'football');
insert into interest (user_id, topic) values (298, 'anime');
insert into interest (user_id, topic) values (299, 'series');
insert into interest (user_id, topic) values (300, 'e-games');
insert into interest (user_id, topic) values (301, 'cinema');
insert into interest (user_id, topic) values (302, 'science');
insert into interest (user_id, topic) values (303, 'music');
insert into interest (user_id, topic) values (304, 'self improvement');
insert into interest (user_id, topic) values (305, 'art');
insert into interest (user_id, topic) values (306, 'make up');
insert into interest (user_id, topic) values (307, 'science');
insert into interest (user_id, topic) values (308, 'science');
insert into interest (user_id, topic) values (309, 'movies');
insert into interest (user_id, topic) values (310, 'movies');
insert into interest (user_id, topic) values (311, 'food');
insert into interest (user_id, topic) values (312, 'football');
insert into interest (user_id, topic) values (313, 'self improvement');
insert into interest (user_id, topic) values (314, 'food');
insert into interest (user_id, topic) values (315, 'movies');
insert into interest (user_id, topic) values (316, 'reading');
insert into interest (user_id, topic) values (317, 'reading');
insert into interest (user_id, topic) values (318, 'music');
insert into interest (user_id, topic) values (319, 'swimming');
insert into interest (user_id, topic) values (320, 'food');
insert into interest (user_id, topic) values (321, 'football');
insert into interest (user_id, topic) values (322, 'movies');
insert into interest (user_id, topic) values (323, 'food');
insert into interest (user_id, topic) values (324, 'music');
insert into interest (user_id, topic) values (325, 'reading');
insert into interest (user_id, topic) values (326, 'make up');
insert into interest (user_id, topic) values (327, 'self improvement');
insert into interest (user_id, topic) values (328, 'science');
insert into interest (user_id, topic) values (329, 'art');
insert into interest (user_id, topic) values (330, 'e-games');
insert into interest (user_id, topic) values (331, 'music');
insert into interest (user_id, topic) values (332, 'series');
insert into interest (user_id, topic) values (333, 'movies');
insert into interest (user_id, topic) values (334, 'self improvement');
insert into interest (user_id, topic) values (335, 'swimming');
insert into interest (user_id, topic) values (336, 'football');
insert into interest (user_id, topic) values (337, 'movies');
insert into interest (user_id, topic) values (338, 'music');
insert into interest (user_id, topic) values (339, 'football');
insert into interest (user_id, topic) values (340, 'music');
insert into interest (user_id, topic) values (341, 'science');
insert into interest (user_id, topic) values (342, 'movies');
insert into interest (user_id, topic) values (343, 'tech');
insert into interest (user_id, topic) values (344, 'art');
insert into interest (user_id, topic) values (345, 'swimming');
insert into interest (user_id, topic) values (346, 'cinema');
insert into interest (user_id, topic) values (347, 'cinema');
insert into interest (user_id, topic) values (348, 'swimming');
insert into interest (user_id, topic) values (349, 'food');
insert into interest (user_id, topic) values (350, 'make up');
insert into interest (user_id, topic) values (351, 'tech');
insert into interest (user_id, topic) values (352, 'reading');
insert into interest (user_id, topic) values (353, 'self improvement');
insert into interest (user_id, topic) values (354, 'food');
insert into interest (user_id, topic) values (355, 'make up');
insert into interest (user_id, topic) values (356, 'football');
insert into interest (user_id, topic) values (357, 'movies');
insert into interest (user_id, topic) values (358, 'movies');
insert into interest (user_id, topic) values (359, 'self improvement');
insert into interest (user_id, topic) values (360, 'make up');
insert into interest (user_id, topic) values (361, 'make up');
insert into interest (user_id, topic) values (362, 'music');
insert into interest (user_id, topic) values (363, 'food');
insert into interest (user_id, topic) values (364, 'series');
insert into interest (user_id, topic) values (365, 'e-games');
insert into interest (user_id, topic) values (366, 'food');
insert into interest (user_id, topic) values (367, 'food');
insert into interest (user_id, topic) values (368, 'tech');
insert into interest (user_id, topic) values (369, 'science');
insert into interest (user_id, topic) values (370, 'science');
insert into interest (user_id, topic) values (371, 'swimming');
insert into interest (user_id, topic) values (372, 'series');
insert into interest (user_id, topic) values (373, 'football');
insert into interest (user_id, topic) values (374, 'reading');
insert into interest (user_id, topic) values (375, 'movies');
insert into interest (user_id, topic) values (376, 'reading');
insert into interest (user_id, topic) values (377, 'football');
insert into interest (user_id, topic) values (378, 'tech');
insert into interest (user_id, topic) values (379, 'tech');
insert into interest (user_id, topic) values (380, 'football');
insert into interest (user_id, topic) values (381, 'movies');
insert into interest (user_id, topic) values (382, 'football');
insert into interest (user_id, topic) values (383, 'anime');
insert into interest (user_id, topic) values (384, 'food');
insert into interest (user_id, topic) values (385, 'food');
insert into interest (user_id, topic) values (386, 'make up');
insert into interest (user_id, topic) values (387, 'cinema');
insert into interest (user_id, topic) values (388, 'food');
insert into interest (user_id, topic) values (389, 'movies');
insert into interest (user_id, topic) values (390, 'art');
insert into interest (user_id, topic) values (391, 'art');
insert into interest (user_id, topic) values (392, 'art');
insert into interest (user_id, topic) values (393, 'food');
insert into interest (user_id, topic) values (394, 'tech');
insert into interest (user_id, topic) values (395, 'make up');
insert into interest (user_id, topic) values (396, 'make up');
insert into interest (user_id, topic) values (397, 'swimming');
insert into interest (user_id, topic) values (398, 'series');
insert into interest (user_id, topic) values (399, 'football');
insert into interest (user_id, topic) values (400, 'football');
insert into interest (user_id, topic) values (401, 'swimming');
insert into interest (user_id, topic) values (402, 'e-games');
insert into interest (user_id, topic) values (403, 'food');
insert into interest (user_id, topic) values (404, 'swimming');
insert into interest (user_id, topic) values (405, 'make up');
insert into interest (user_id, topic) values (406, 'series');
insert into interest (user_id, topic) values (407, 'cinema');
insert into interest (user_id, topic) values (408, 'food');
insert into interest (user_id, topic) values (409, 'art');
insert into interest (user_id, topic) values (410, 'tech');
insert into interest (user_id, topic) values (411, 'tech');
insert into interest (user_id, topic) values (412, 'football');
insert into interest (user_id, topic) values (413, 'art');
insert into interest (user_id, topic) values (414, 'series');
insert into interest (user_id, topic) values (415, 'football');
insert into interest (user_id, topic) values (416, 'music');
insert into interest (user_id, topic) values (417, 'food');
insert into interest (user_id, topic) values (418, 'swimming');
insert into interest (user_id, topic) values (419, 'music');
insert into interest (user_id, topic) values (420, 'cinema');
insert into interest (user_id, topic) values (421, 'football');
insert into interest (user_id, topic) values (422, 'cinema');
insert into interest (user_id, topic) values (423, 'football');
insert into interest (user_id, topic) values (424, 'movies');
insert into interest (user_id, topic) values (425, 'food');
insert into interest (user_id, topic) values (426, 'self improvement');
insert into interest (user_id, topic) values (427, 'anime');
insert into interest (user_id, topic) values (428, 'art');
insert into interest (user_id, topic) values (429, 'e-games');
insert into interest (user_id, topic) values (430, 'make up');
insert into interest (user_id, topic) values (431, 'cinema');
insert into interest (user_id, topic) values (432, 'series');
insert into interest (user_id, topic) values (433, 'art');
insert into interest (user_id, topic) values (434, 'make up');
insert into interest (user_id, topic) values (435, 'anime');
insert into interest (user_id, topic) values (436, 'science');
insert into interest (user_id, topic) values (437, 'series');
insert into interest (user_id, topic) values (438, 'make up');
insert into interest (user_id, topic) values (439, 'art');
insert into interest (user_id, topic) values (440, 'art');
insert into interest (user_id, topic) values (441, 'food');
insert into interest (user_id, topic) values (442, 'football');
insert into interest (user_id, topic) values (443, 'movies');
insert into interest (user_id, topic) values (444, 'football');
insert into interest (user_id, topic) values (445, 'series');
insert into interest (user_id, topic) values (446, 'swimming');
insert into interest (user_id, topic) values (447, 'e-games');
insert into interest (user_id, topic) values (448, 'tech');
insert into interest (user_id, topic) values (449, 'cinema');
insert into interest (user_id, topic) values (450, 'anime');
insert into interest (user_id, topic) values (451, 'self improvement');
insert into interest (user_id, topic) values (452, 'reading');
insert into interest (user_id, topic) values (453, 'make up');
insert into interest (user_id, topic) values (454, 'reading');
insert into interest (user_id, topic) values (455, 'make up');
insert into interest (user_id, topic) values (456, 'cinema');
insert into interest (user_id, topic) values (457, 'movies');
insert into interest (user_id, topic) values (458, 'anime');
insert into interest (user_id, topic) values (459, 'cinema');
insert into interest (user_id, topic) values (460, 'reading');
insert into interest (user_id, topic) values (461, 'anime');
insert into interest (user_id, topic) values (462, 'cinema');
insert into interest (user_id, topic) values (463, 'reading');
insert into interest (user_id, topic) values (464, 'food');
insert into interest (user_id, topic) values (465, 'tech');
insert into interest (user_id, topic) values (466, 'music');
insert into interest (user_id, topic) values (467, 'make up');
insert into interest (user_id, topic) values (468, 'anime');
insert into interest (user_id, topic) values (469, 'food');
insert into interest (user_id, topic) values (470, 'series');
insert into interest (user_id, topic) values (471, 'tech');
insert into interest (user_id, topic) values (472, 'football');
insert into interest (user_id, topic) values (473, 'music');
insert into interest (user_id, topic) values (474, 'art');
insert into interest (user_id, topic) values (475, 'reading');
insert into interest (user_id, topic) values (476, 'tech');
insert into interest (user_id, topic) values (477, 'reading');
insert into interest (user_id, topic) values (478, 'food');
insert into interest (user_id, topic) values (479, 'food');
insert into interest (user_id, topic) values (480, 'art');
insert into interest (user_id, topic) values (481, 'movies');
insert into interest (user_id, topic) values (482, 'movies');
insert into interest (user_id, topic) values (483, 'make up');
insert into interest (user_id, topic) values (484, 'reading');
insert into interest (user_id, topic) values (485, 'tech');
insert into interest (user_id, topic) values (486, 'cinema');
insert into interest (user_id, topic) values (487, 'e-games');
insert into interest (user_id, topic) values (488, 'science');
insert into interest (user_id, topic) values (489, 'science');
insert into interest (user_id, topic) values (490, 'series');
insert into interest (user_id, topic) values (491, 'e-games');
insert into interest (user_id, topic) values (492, 'food');
insert into interest (user_id, topic) values (493, 'reading');
insert into interest (user_id, topic) values (494, 'cinema');
insert into interest (user_id, topic) values (495, 'series');
insert into interest (user_id, topic) values (496, 'music');
insert into interest (user_id, topic) values (497, 'make up');
insert into interest (user_id, topic) values (498, 'music');
insert into interest (user_id, topic) values (499, 'music');
insert into interest (user_id, topic) values (500, 'self improvement');
insert into interest (user_id, topic) values (501, 'tech');
insert into interest (user_id, topic) values (502, 'series');
insert into interest (user_id, topic) values (503, 'music');
insert into interest (user_id, topic) values (504, 'series');
insert into interest (user_id, topic) values (505, 'movies');
insert into interest (user_id, topic) values (506, 'make up');
insert into interest (user_id, topic) values (507, 'art');
insert into interest (user_id, topic) values (508, 'movies');
insert into interest (user_id, topic) values (509, 'art');
insert into interest (user_id, topic) values (510, 'anime');
insert into interest (user_id, topic) values (511, 'music');
insert into interest (user_id, topic) values (512, 'art');
insert into interest (user_id, topic) values (513, 'self improvement');
insert into interest (user_id, topic) values (514, 'tech');
insert into interest (user_id, topic) values (515, 'reading');
insert into interest (user_id, topic) values (516, 'self improvement');
insert into interest (user_id, topic) values (517, 'make up');
insert into interest (user_id, topic) values (518, 'swimming');
insert into interest (user_id, topic) values (519, 'make up');
insert into interest (user_id, topic) values (520, 'series');
insert into interest (user_id, topic) values (521, 'art');
insert into interest (user_id, topic) values (522, 'swimming');
insert into interest (user_id, topic) values (523, 'e-games');
insert into interest (user_id, topic) values (524, 'self improvement');
insert into interest (user_id, topic) values (525, 'anime');
insert into interest (user_id, topic) values (526, 'food');
insert into interest (user_id, topic) values (527, 'football');
insert into interest (user_id, topic) values (528, 'football');
insert into interest (user_id, topic) values (529, 'series');
insert into interest (user_id, topic) values (530, 'swimming');
insert into interest (user_id, topic) values (531, 'football');
insert into interest (user_id, topic) values (532, 'self improvement');
insert into interest (user_id, topic) values (533, 'cinema');
insert into interest (user_id, topic) values (534, 'make up');
insert into interest (user_id, topic) values (535, 'food');
insert into interest (user_id, topic) values (536, 'swimming');
insert into interest (user_id, topic) values (537, 'movies');
insert into interest (user_id, topic) values (538, 'art');
insert into interest (user_id, topic) values (539, 'anime');
insert into interest (user_id, topic) values (540, 'art');
insert into interest (user_id, topic) values (541, 'movies');
insert into interest (user_id, topic) values (542, 'make up');
insert into interest (user_id, topic) values (543, 'swimming');
insert into interest (user_id, topic) values (544, 'cinema');
insert into interest (user_id, topic) values (545, 'football');
insert into interest (user_id, topic) values (546, 'football');
insert into interest (user_id, topic) values (547, 'swimming');
insert into interest (user_id, topic) values (548, 'reading');
insert into interest (user_id, topic) values (549, 'anime');
insert into interest (user_id, topic) values (550, 'science');
insert into interest (user_id, topic) values (551, 'cinema');
insert into interest (user_id, topic) values (552, 'e-games');
insert into interest (user_id, topic) values (553, 'food');
insert into interest (user_id, topic) values (554, 'swimming');
insert into interest (user_id, topic) values (555, 'football');
insert into interest (user_id, topic) values (556, 'food');
insert into interest (user_id, topic) values (557, 'tech');
insert into interest (user_id, topic) values (558, 'movies');
insert into interest (user_id, topic) values (559, 'tech');
insert into interest (user_id, topic) values (560, 'make up');
insert into interest (user_id, topic) values (561, 'art');
insert into interest (user_id, topic) values (562, 'tech');
insert into interest (user_id, topic) values (563, 'e-games');
insert into interest (user_id, topic) values (564, 'make up');
insert into interest (user_id, topic) values (565, 'swimming');
insert into interest (user_id, topic) values (566, 'football');
insert into interest (user_id, topic) values (567, 'reading');
insert into interest (user_id, topic) values (568, 'art');
insert into interest (user_id, topic) values (569, 'anime');
insert into interest (user_id, topic) values (570, 'make up');
insert into interest (user_id, topic) values (571, 'series');
insert into interest (user_id, topic) values (572, 'football');
insert into interest (user_id, topic) values (573, 'science');
insert into interest (user_id, topic) values (574, 'anime');
insert into interest (user_id, topic) values (575, 'music');
insert into interest (user_id, topic) values (576, 'series');
insert into interest (user_id, topic) values (577, 'art');
insert into interest (user_id, topic) values (578, 'e-games');
insert into interest (user_id, topic) values (579, 'anime');
insert into interest (user_id, topic) values (580, 'music');
insert into interest (user_id, topic) values (581, 'series');
insert into interest (user_id, topic) values (582, 'series');
insert into interest (user_id, topic) values (583, 'e-games');
insert into interest (user_id, topic) values (584, 'make up');
insert into interest (user_id, topic) values (585, 'art');
insert into interest (user_id, topic) values (586, 'science');
insert into interest (user_id, topic) values (587, 'science');
insert into interest (user_id, topic) values (588, 'food');
insert into interest (user_id, topic) values (589, 'football');
insert into interest (user_id, topic) values (590, 'tech');
insert into interest (user_id, topic) values (591, 'science');
insert into interest (user_id, topic) values (592, 'make up');
insert into interest (user_id, topic) values (593, 'swimming');
insert into interest (user_id, topic) values (594, 'art');
insert into interest (user_id, topic) values (595, 'make up');
insert into interest (user_id, topic) values (596, 'music');
insert into interest (user_id, topic) values (597, 'series');
insert into interest (user_id, topic) values (598, 'art');
insert into interest (user_id, topic) values (599, 'food');
insert into interest (user_id, topic) values (600, 'cinema');
insert into interest (user_id, topic) values (601, 'cinema');
insert into interest (user_id, topic) values (602, 'series');
insert into interest (user_id, topic) values (603, 'self improvement');
insert into interest (user_id, topic) values (604, 'food');
insert into interest (user_id, topic) values (605, 'e-games');
insert into interest (user_id, topic) values (606, 'anime');
insert into interest (user_id, topic) values (607, 'tech');
insert into interest (user_id, topic) values (608, 'reading');
insert into interest (user_id, topic) values (609, 'e-games');
insert into interest (user_id, topic) values (610, 'cinema');
insert into interest (user_id, topic) values (611, 'art');
insert into interest (user_id, topic) values (612, 'e-games');
insert into interest (user_id, topic) values (613, 'swimming');
insert into interest (user_id, topic) values (614, 'food');
insert into interest (user_id, topic) values (615, 'art');
insert into interest (user_id, topic) values (616, 'series');
insert into interest (user_id, topic) values (617, 'swimming');
insert into interest (user_id, topic) values (618, 'e-games');
insert into interest (user_id, topic) values (619, 'music');
insert into interest (user_id, topic) values (620, 'movies');
insert into interest (user_id, topic) values (621, 'science');
insert into interest (user_id, topic) values (622, 'swimming');
insert into interest (user_id, topic) values (623, 'anime');
insert into interest (user_id, topic) values (624, 'art');
insert into interest (user_id, topic) values (625, 'movies');
insert into interest (user_id, topic) values (626, 'cinema');
insert into interest (user_id, topic) values (627, 'anime');
insert into interest (user_id, topic) values (628, 'self improvement');
insert into interest (user_id, topic) values (629, 'food');
insert into interest (user_id, topic) values (630, 'series');
insert into interest (user_id, topic) values (631, 'cinema');
insert into interest (user_id, topic) values (632, 'anime');
insert into interest (user_id, topic) values (633, 'science');
insert into interest (user_id, topic) values (634, 'art');
insert into interest (user_id, topic) values (635, 'cinema');
insert into interest (user_id, topic) values (636, 'series');
insert into interest (user_id, topic) values (637, 'cinema');
insert into interest (user_id, topic) values (638, 'science');
insert into interest (user_id, topic) values (639, 'make up');
insert into interest (user_id, topic) values (640, 'series');
insert into interest (user_id, topic) values (641, 'movies');
insert into interest (user_id, topic) values (642, 'cinema');
insert into interest (user_id, topic) values (643, 'anime');
insert into interest (user_id, topic) values (644, 'music');
insert into interest (user_id, topic) values (645, 'cinema');
insert into interest (user_id, topic) values (646, 'series');
insert into interest (user_id, topic) values (647, 'anime');
insert into interest (user_id, topic) values (648, 'tech');
insert into interest (user_id, topic) values (649, 'anime');
insert into interest (user_id, topic) values (650, 'series');
insert into interest (user_id, topic) values (651, 'tech');
insert into interest (user_id, topic) values (652, 'make up');
insert into interest (user_id, topic) values (653, 'tech');
insert into interest (user_id, topic) values (654, 'swimming');
insert into interest (user_id, topic) values (655, 'self improvement');
insert into interest (user_id, topic) values (656, 'art');
insert into interest (user_id, topic) values (657, 'series');
insert into interest (user_id, topic) values (658, 'self improvement');
insert into interest (user_id, topic) values (659, 'anime');
insert into interest (user_id, topic) values (660, 'art');
insert into interest (user_id, topic) values (661, 'anime');
insert into interest (user_id, topic) values (662, 'tech');
insert into interest (user_id, topic) values (663, 'series');
insert into interest (user_id, topic) values (664, 'tech');
insert into interest (user_id, topic) values (665, 'tech');
insert into interest (user_id, topic) values (666, 'e-games');
insert into interest (user_id, topic) values (667, 'music');
insert into interest (user_id, topic) values (668, 'movies');
insert into interest (user_id, topic) values (669, 'food');
insert into interest (user_id, topic) values (670, 'food');
insert into interest (user_id, topic) values (671, 'anime');
insert into interest (user_id, topic) values (672, 'tech');
insert into interest (user_id, topic) values (673, 'food');
insert into interest (user_id, topic) values (674, 'cinema');
insert into interest (user_id, topic) values (675, 'reading');
insert into interest (user_id, topic) values (676, 'cinema');
insert into interest (user_id, topic) values (677, 'music');
insert into interest (user_id, topic) values (678, 'movies');
insert into interest (user_id, topic) values (679, 'science');
insert into interest (user_id, topic) values (680, 'movies');
insert into interest (user_id, topic) values (681, 'tech');
insert into interest (user_id, topic) values (682, 'series');
insert into interest (user_id, topic) values (683, 'series');
insert into interest (user_id, topic) values (684, 'cinema');
insert into interest (user_id, topic) values (685, 'music');
insert into interest (user_id, topic) values (686, 'art');
insert into interest (user_id, topic) values (687, 'reading');
insert into interest (user_id, topic) values (688, 'e-games');
insert into interest (user_id, topic) values (689, 'art');
insert into interest (user_id, topic) values (690, 'reading');
insert into interest (user_id, topic) values (691, 'tech');
insert into interest (user_id, topic) values (692, 'self improvement');
insert into interest (user_id, topic) values (693, 'reading');
insert into interest (user_id, topic) values (694, 'cinema');
insert into interest (user_id, topic) values (695, 'movies');
insert into interest (user_id, topic) values (696, 'reading');
insert into interest (user_id, topic) values (697, 'self improvement');
insert into interest (user_id, topic) values (698, 'anime');
insert into interest (user_id, topic) values (699, 'tech');
insert into interest (user_id, topic) values (700, 'tech');
insert into interest (user_id, topic) values (701, 'make up');
insert into interest (user_id, topic) values (702, 'football');
insert into interest (user_id, topic) values (703, 'movies');
insert into interest (user_id, topic) values (704, 'make up');
insert into interest (user_id, topic) values (705, 'swimming');
insert into interest (user_id, topic) values (706, 'tech');
insert into interest (user_id, topic) values (707, 'reading');
insert into interest (user_id, topic) values (708, 'series');
insert into interest (user_id, topic) values (709, 'cinema');
insert into interest (user_id, topic) values (710, 'reading');
insert into interest (user_id, topic) values (711, 'swimming');
insert into interest (user_id, topic) values (712, 'music');
insert into interest (user_id, topic) values (713, 'food');
insert into interest (user_id, topic) values (714, 'cinema');
insert into interest (user_id, topic) values (715, 'series');
insert into interest (user_id, topic) values (716, 'anime');
insert into interest (user_id, topic) values (717, 'science');
insert into interest (user_id, topic) values (718, 'anime');
insert into interest (user_id, topic) values (719, 'e-games');
insert into interest (user_id, topic) values (720, 'anime');
insert into interest (user_id, topic) values (721, 'food');
insert into interest (user_id, topic) values (722, 'cinema');
insert into interest (user_id, topic) values (723, 'music');
insert into interest (user_id, topic) values (724, 'food');
insert into interest (user_id, topic) values (725, 'anime');
insert into interest (user_id, topic) values (726, 'swimming');
insert into interest (user_id, topic) values (727, 'movies');
insert into interest (user_id, topic) values (728, 'art');
insert into interest (user_id, topic) values (729, 'football');
insert into interest (user_id, topic) values (730, 'art');
insert into interest (user_id, topic) values (731, 'self improvement');
insert into interest (user_id, topic) values (732, 'cinema');
insert into interest (user_id, topic) values (733, 'anime');
insert into interest (user_id, topic) values (734, 'cinema');
insert into interest (user_id, topic) values (735, 'cinema');
insert into interest (user_id, topic) values (736, 'make up');
insert into interest (user_id, topic) values (737, 'anime');
insert into interest (user_id, topic) values (738, 'music');
insert into interest (user_id, topic) values (739, 'art');
insert into interest (user_id, topic) values (740, 'football');
insert into interest (user_id, topic) values (741, 'cinema');
insert into interest (user_id, topic) values (742, 'football');
insert into interest (user_id, topic) values (743, 'swimming');
insert into interest (user_id, topic) values (744, 'art');
insert into interest (user_id, topic) values (745, 'anime');
insert into interest (user_id, topic) values (746, 'music');
insert into interest (user_id, topic) values (747, 'anime');
insert into interest (user_id, topic) values (748, 'cinema');
insert into interest (user_id, topic) values (749, 'self improvement');
insert into interest (user_id, topic) values (750, 'anime');
insert into interest (user_id, topic) values (751, 'series');
insert into interest (user_id, topic) values (752, 'music');
insert into interest (user_id, topic) values (753, 'e-games');
insert into interest (user_id, topic) values (754, 'anime');
insert into interest (user_id, topic) values (755, 'science');
insert into interest (user_id, topic) values (756, 'self improvement');
insert into interest (user_id, topic) values (757, 'cinema');
insert into interest (user_id, topic) values (758, 'reading');
insert into interest (user_id, topic) values (759, 'swimming');
insert into interest (user_id, topic) values (760, 'self improvement');
insert into interest (user_id, topic) values (761, 'music');
insert into interest (user_id, topic) values (762, 'anime');
insert into interest (user_id, topic) values (763, 'music');
insert into interest (user_id, topic) values (764, 'food');
insert into interest (user_id, topic) values (765, 'series');
insert into interest (user_id, topic) values (766, 'music');
insert into interest (user_id, topic) values (767, 'food');
insert into interest (user_id, topic) values (768, 'science');
insert into interest (user_id, topic) values (769, 'series');
insert into interest (user_id, topic) values (770, 'music');
insert into interest (user_id, topic) values (771, 'music');
insert into interest (user_id, topic) values (772, 'series');
insert into interest (user_id, topic) values (773, 'e-games');
insert into interest (user_id, topic) values (774, 'make up');
insert into interest (user_id, topic) values (775, 'science');
insert into interest (user_id, topic) values (776, 'movies');
insert into interest (user_id, topic) values (777, 'series');
insert into interest (user_id, topic) values (778, 'series');
insert into interest (user_id, topic) values (779, 'make up');
insert into interest (user_id, topic) values (780, 'series');
insert into interest (user_id, topic) values (781, 'art');
insert into interest (user_id, topic) values (782, 'reading');
insert into interest (user_id, topic) values (783, 'tech');
insert into interest (user_id, topic) values (784, 'reading');
insert into interest (user_id, topic) values (785, 'science');
insert into interest (user_id, topic) values (786, 'food');
insert into interest (user_id, topic) values (787, 'music');
insert into interest (user_id, topic) values (788, 'make up');
insert into interest (user_id, topic) values (789, 'science');
insert into interest (user_id, topic) values (790, 'science');
insert into interest (user_id, topic) values (791, 'anime');
insert into interest (user_id, topic) values (792, 'science');
insert into interest (user_id, topic) values (793, 'tech');
insert into interest (user_id, topic) values (794, 'swimming');
insert into interest (user_id, topic) values (795, 'football');
insert into interest (user_id, topic) values (796, 'anime');
insert into interest (user_id, topic) values (797, 'cinema');
insert into interest (user_id, topic) values (798, 'cinema');
insert into interest (user_id, topic) values (799, 'make up');
insert into interest (user_id, topic) values (800, 'e-games');
insert into interest (user_id, topic) values (801, 'make up');
insert into interest (user_id, topic) values (802, 'make up');
insert into interest (user_id, topic) values (803, 'science');
insert into interest (user_id, topic) values (804, 'self improvement');
insert into interest (user_id, topic) values (805, 'e-games');
insert into interest (user_id, topic) values (806, 'food');
insert into interest (user_id, topic) values (807, 'tech');
insert into interest (user_id, topic) values (808, 'music');
insert into interest (user_id, topic) values (809, 'series');
insert into interest (user_id, topic) values (810, 'food');
insert into interest (user_id, topic) values (811, 'football');
insert into interest (user_id, topic) values (812, 'music');
insert into interest (user_id, topic) values (813, 'tech');
insert into interest (user_id, topic) values (814, 'football');
insert into interest (user_id, topic) values (815, 'tech');
insert into interest (user_id, topic) values (816, 'swimming');
insert into interest (user_id, topic) values (817, 'self improvement');
insert into interest (user_id, topic) values (818, 'series');
insert into interest (user_id, topic) values (819, 'science');
insert into interest (user_id, topic) values (820, 'football');
insert into interest (user_id, topic) values (821, 'anime');
insert into interest (user_id, topic) values (822, 'anime');
insert into interest (user_id, topic) values (823, 'reading');
insert into interest (user_id, topic) values (824, 'e-games');
insert into interest (user_id, topic) values (825, 'science');
insert into interest (user_id, topic) values (826, 'reading');
insert into interest (user_id, topic) values (827, 'football');
insert into interest (user_id, topic) values (828, 'art');
insert into interest (user_id, topic) values (829, 'reading');
insert into interest (user_id, topic) values (830, 'cinema');
insert into interest (user_id, topic) values (831, 'food');
insert into interest (user_id, topic) values (832, 'football');
insert into interest (user_id, topic) values (833, 'series');
insert into interest (user_id, topic) values (834, 'cinema');
insert into interest (user_id, topic) values (835, 'make up');
insert into interest (user_id, topic) values (836, 'art');
insert into interest (user_id, topic) values (837, 'reading');
insert into interest (user_id, topic) values (838, 'movies');
insert into interest (user_id, topic) values (839, 'movies');
insert into interest (user_id, topic) values (840, 'football');
insert into interest (user_id, topic) values (841, 'tech');
insert into interest (user_id, topic) values (842, 'cinema');
insert into interest (user_id, topic) values (843, 'science');
insert into interest (user_id, topic) values (844, 'music');
insert into interest (user_id, topic) values (845, 'cinema');
insert into interest (user_id, topic) values (846, 'reading');
insert into interest (user_id, topic) values (847, 'tech');
insert into interest (user_id, topic) values (848, 'movies');
insert into interest (user_id, topic) values (849, 'science');
insert into interest (user_id, topic) values (850, 'tech');
insert into interest (user_id, topic) values (851, 'reading');
insert into interest (user_id, topic) values (852, 'music');
insert into interest (user_id, topic) values (853, 'e-games');
insert into interest (user_id, topic) values (854, 'reading');
insert into interest (user_id, topic) values (855, 'music');
insert into interest (user_id, topic) values (856, 'football');
insert into interest (user_id, topic) values (857, 'make up');
insert into interest (user_id, topic) values (858, 'reading');
insert into interest (user_id, topic) values (859, 'swimming');
insert into interest (user_id, topic) values (860, 'series');
insert into interest (user_id, topic) values (861, 'football');
insert into interest (user_id, topic) values (862, 'cinema');
insert into interest (user_id, topic) values (863, 'swimming');
insert into interest (user_id, topic) values (864, 'tech');
insert into interest (user_id, topic) values (865, 'e-games');
insert into interest (user_id, topic) values (866, 'food');
insert into interest (user_id, topic) values (867, 'anime');
insert into interest (user_id, topic) values (868, 'reading');
insert into interest (user_id, topic) values (869, 'swimming');
insert into interest (user_id, topic) values (870, 'make up');
insert into interest (user_id, topic) values (871, 'music');
insert into interest (user_id, topic) values (872, 'make up');
insert into interest (user_id, topic) values (873, 'food');
insert into interest (user_id, topic) values (874, 'self improvement');
insert into interest (user_id, topic) values (875, 'reading');
insert into interest (user_id, topic) values (876, 'music');
insert into interest (user_id, topic) values (877, 'food');
insert into interest (user_id, topic) values (878, 'e-games');
insert into interest (user_id, topic) values (879, 'make up');
insert into interest (user_id, topic) values (880, 'e-games');
insert into interest (user_id, topic) values (881, 'cinema');
insert into interest (user_id, topic) values (882, 'make up');
insert into interest (user_id, topic) values (883, 'swimming');
insert into interest (user_id, topic) values (884, 'cinema');
insert into interest (user_id, topic) values (885, 'make up');
insert into interest (user_id, topic) values (886, 'e-games');
insert into interest (user_id, topic) values (887, 'anime');
insert into interest (user_id, topic) values (888, 'music');
insert into interest (user_id, topic) values (889, 'food');
insert into interest (user_id, topic) values (890, 'swimming');
insert into interest (user_id, topic) values (891, 'reading');
insert into interest (user_id, topic) values (892, 'make up');
insert into interest (user_id, topic) values (893, 'make up');
insert into interest (user_id, topic) values (894, 'movies');
insert into interest (user_id, topic) values (895, 'self improvement');
insert into interest (user_id, topic) values (896, 'swimming');
insert into interest (user_id, topic) values (897, 'make up');
insert into interest (user_id, topic) values (898, 'self improvement');
insert into interest (user_id, topic) values (899, 'food');
insert into interest (user_id, topic) values (900, 'e-games');
insert into interest (user_id, topic) values (901, 'music');
insert into interest (user_id, topic) values (902, 'swimming');
insert into interest (user_id, topic) values (903, 'football');
insert into interest (user_id, topic) values (904, 'reading');
insert into interest (user_id, topic) values (905, 'anime');
insert into interest (user_id, topic) values (906, 'tech');
insert into interest (user_id, topic) values (907, 'tech');
insert into interest (user_id, topic) values (908, 'e-games');
insert into interest (user_id, topic) values (909, 'tech');
insert into interest (user_id, topic) values (910, 'food');
insert into interest (user_id, topic) values (911, 'anime');
insert into interest (user_id, topic) values (912, 'food');
insert into interest (user_id, topic) values (913, 'music');
insert into interest (user_id, topic) values (914, 'e-games');
insert into interest (user_id, topic) values (915, 'tech');
insert into interest (user_id, topic) values (916, 'science');
insert into interest (user_id, topic) values (917, 'science');
insert into interest (user_id, topic) values (918, 'e-games');
insert into interest (user_id, topic) values (919, 'series');
insert into interest (user_id, topic) values (920, 'self improvement');
insert into interest (user_id, topic) values (921, 'movies');
insert into interest (user_id, topic) values (922, 'art');
insert into interest (user_id, topic) values (923, 'make up');
insert into interest (user_id, topic) values (924, 'cinema');
insert into interest (user_id, topic) values (925, 'anime');
insert into interest (user_id, topic) values (926, 'tech');
insert into interest (user_id, topic) values (927, 'make up');
insert into interest (user_id, topic) values (928, 'football');
insert into interest (user_id, topic) values (929, 'reading');
insert into interest (user_id, topic) values (930, 'reading');
insert into interest (user_id, topic) values (931, 'self improvement');
insert into interest (user_id, topic) values (932, 'e-games');
insert into interest (user_id, topic) values (933, 'movies');
insert into interest (user_id, topic) values (934, 'cinema');
insert into interest (user_id, topic) values (935, 'football');
insert into interest (user_id, topic) values (936, 'e-games');
insert into interest (user_id, topic) values (937, 'football');
insert into interest (user_id, topic) values (938, 'anime');
insert into interest (user_id, topic) values (939, 'series');
insert into interest (user_id, topic) values (940, 'self improvement');
insert into interest (user_id, topic) values (941, 'self improvement');
insert into interest (user_id, topic) values (942, 'anime');
insert into interest (user_id, topic) values (943, 'series');
insert into interest (user_id, topic) values (944, 'cinema');
insert into interest (user_id, topic) values (945, 'self improvement');
insert into interest (user_id, topic) values (946, 'make up');
insert into interest (user_id, topic) values (947, 'art');
insert into interest (user_id, topic) values (948, 'reading');
insert into interest (user_id, topic) values (949, 'science');
insert into interest (user_id, topic) values (950, 'art');
insert into interest (user_id, topic) values (951, 'art');
insert into interest (user_id, topic) values (952, 'food');
insert into interest (user_id, topic) values (953, 'football');
insert into interest (user_id, topic) values (954, 'self improvement');
insert into interest (user_id, topic) values (955, 'anime');
insert into interest (user_id, topic) values (956, 'tech');
insert into interest (user_id, topic) values (957, 'e-games');
insert into interest (user_id, topic) values (958, 'science');
insert into interest (user_id, topic) values (959, 'food');
insert into interest (user_id, topic) values (960, 'series');
insert into interest (user_id, topic) values (961, 'swimming');
insert into interest (user_id, topic) values (962, 'self improvement');
insert into interest (user_id, topic) values (963, 'tech');
insert into interest (user_id, topic) values (964, 'reading');
insert into interest (user_id, topic) values (965, 'food');
insert into interest (user_id, topic) values (966, 'science');
insert into interest (user_id, topic) values (967, 'anime');
insert into interest (user_id, topic) values (968, 'reading');
insert into interest (user_id, topic) values (969, 'swimming');
insert into interest (user_id, topic) values (970, 'music');
insert into interest (user_id, topic) values (971, 'reading');
insert into interest (user_id, topic) values (972, 'swimming');
insert into interest (user_id, topic) values (973, 'movies');
insert into interest (user_id, topic) values (974, 'swimming');
insert into interest (user_id, topic) values (975, 'food');
insert into interest (user_id, topic) values (976, 'make up');
insert into interest (user_id, topic) values (977, 'cinema');
insert into interest (user_id, topic) values (978, 'cinema');
insert into interest (user_id, topic) values (979, 'tech');
insert into interest (user_id, topic) values (980, 'cinema');
insert into interest (user_id, topic) values (981, 'self improvement');
insert into interest (user_id, topic) values (982, 'swimming');
insert into interest (user_id, topic) values (983, 'e-games');
insert into interest (user_id, topic) values (984, 'art');
insert into interest (user_id, topic) values (985, 'reading');
insert into interest (user_id, topic) values (986, 'food');
insert into interest (user_id, topic) values (987, 'swimming');
insert into interest (user_id, topic) values (988, 'football');
insert into interest (user_id, topic) values (989, 'cinema');
insert into interest (user_id, topic) values (990, 'e-games');
insert into interest (user_id, topic) values (991, 'swimming');
insert into interest (user_id, topic) values (992, 'music');
insert into interest (user_id, topic) values (993, 'make up');
insert into interest (user_id, topic) values (994, 'make up');
insert into interest (user_id, topic) values (995, 'football');
insert into interest (user_id, topic) values (996, 'food');
insert into interest (user_id, topic) values (997, 'movies');
insert into interest (user_id, topic) values (998, 'e-games');
insert into interest (user_id, topic) values (999, 'football');
insert into interest (user_id, topic) values (1000, 'self improvement');
