insert into interest (user_id, topic) values (1, 'science');
insert into interest (user_id, topic) values (2, 'series');
insert into interest (user_id, topic) values (3, 'e-games');
insert into interest (user_id, topic) values (4, 'anime');
insert into interest (user_id, topic) values (5, 'tech');
insert into interest (user_id, topic) values (6, 'makeUp');
insert into interest (user_id, topic) values (7, 'science');
insert into interest (user_id, topic) values (8, 'food');
insert into interest (user_id, topic) values (9, 'series');
insert into interest (user_id, topic) values (10, 'e-games');
insert into interest (user_id, topic) values (11, 'movies');
insert into interest (user_id, topic) values (12, 'art');
insert into interest (user_id, topic) values (13, 'e-games');
insert into interest (user_id, topic) values (14, 'tech');
insert into interest (user_id, topic) values (15, 'makeUp');
insert into interest (user_id, topic) values (16, 'food');
insert into interest (user_id, topic) values (17, 'series');
insert into interest (user_id, topic) values (18, 'science');
insert into interest (user_id, topic) values (19, 'food');
insert into interest (user_id, topic) values (20, 'cinema');
insert into interest (user_id, topic) values (21, 'music');
insert into interest (user_id, topic) values (22, 'self improvement');
insert into interest (user_id, topic) values (23, 'science');
insert into interest (user_id, topic) values (24, 'science');
insert into interest (user_id, topic) values (25, 'food');
insert into interest (user_id, topic) values (26, 'science');
insert into interest (user_id, topic) values (27, 'movies');
insert into interest (user_id, topic) values (28, 'food');
insert into interest (user_id, topic) values (29, 'food');
insert into interest (user_id, topic) values (30, 'cinema');
insert into interest (user_id, topic) values (31, 'e-games');
insert into interest (user_id, topic) values (32, 'anime');
insert into interest (user_id, topic) values (33, 'makeUp');
insert into interest (user_id, topic) values (34, 'self improvement');
insert into interest (user_id, topic) values (35, 'football');
insert into interest (user_id, topic) values (36, 'cinema');
insert into interest (user_id, topic) values (37, 'art');
insert into interest (user_id, topic) values (38, 'science');
insert into interest (user_id, topic) values (39, 'football');
insert into interest (user_id, topic) values (40, 'anime');
insert into interest (user_id, topic) values (41, 'art');
insert into interest (user_id, topic) values (42, 'tech');
insert into interest (user_id, topic) values (43, 'e-games');
insert into interest (user_id, topic) values (44, 'swimming');
insert into interest (user_id, topic) values (45, 'art');
insert into interest (user_id, topic) values (46, 'movies');
insert into interest (user_id, topic) values (47, 'series');
insert into interest (user_id, topic) values (48, 'football');
insert into interest (user_id, topic) values (49, 'tech');
insert into interest (user_id, topic) values (50, 'science');
insert into interest (user_id, topic) values (1, 'food');
insert into interest (user_id, topic) values (2, 'reading');
insert into interest (user_id, topic) values (3, 'art');
insert into interest (user_id, topic) values (4, 'food');
insert into interest (user_id, topic) values (5, 'science');
insert into interest (user_id, topic) values (6, 'series');
insert into interest (user_id, topic) values (7, 'series');
insert into interest (user_id, topic) values (8, 'football');
insert into interest (user_id, topic) values (9, 'reading');
insert into interest (user_id, topic) values (10, 'e-games');
insert into interest (user_id, topic) values (11, 'swimming');
insert into interest (user_id, topic) values (12, 'swimming');
insert into interest (user_id, topic) values (13, 'anime');
insert into interest (user_id, topic) values (14, 'anime');
insert into interest (user_id, topic) values (15, 'series');
insert into interest (user_id, topic) values (16, 'anime');
insert into interest (user_id, topic) values (17, 'anime');
insert into interest (user_id, topic) values (18, 'makeUp');
insert into interest (user_id, topic) values (19, 'food');
insert into interest (user_id, topic) values (20, 'e-games');
insert into interest (user_id, topic) values (21, 'music');
insert into interest (user_id, topic) values (22, 'movies');
insert into interest (user_id, topic) values (23, 'movies');
insert into interest (user_id, topic) values (24, 'art');
insert into interest (user_id, topic) values (25, 'e-games');
insert into interest (user_id, topic) values (26, 'makeUp');
insert into interest (user_id, topic) values (27, 'reading');
insert into interest (user_id, topic) values (28, 'art');
insert into interest (user_id, topic) values (29, 'reading');
insert into interest (user_id, topic) values (30, 'tech');
insert into interest (user_id, topic) values (31, 'swimming');
insert into interest (user_id, topic) values (32, 'swimming');
insert into interest (user_id, topic) values (33, 'cinema');
insert into interest (user_id, topic) values (34, 'food');
insert into interest (user_id, topic) values (35, 'football');
insert into interest (user_id, topic) values (36, 'makeUp');
insert into interest (user_id, topic) values (37, 'series');
insert into interest (user_id, topic) values (38, 'e-games');
insert into interest (user_id, topic) values (39, 'anime');
insert into interest (user_id, topic) values (40, 'movies');
insert into interest (user_id, topic) values (41, 'cinema');
insert into interest (user_id, topic) values (42, 'reading');
insert into interest (user_id, topic) values (43, 'science');
insert into interest (user_id, topic) values (44, 'art');
insert into interest (user_id, topic) values (45, 'self improvement');
insert into interest (user_id, topic) values (46, 'cinema');
insert into interest (user_id, topic) values (47, 'football');
insert into interest (user_id, topic) values (48, 'e-games');
insert into interest (user_id, topic) values (49, 'e-games');
insert into interest (user_id, topic) values (50, 'reading');
insert into interest (user_id, topic) values ( 1, 'art');
insert into interest (user_id, topic) values ( 2, 'makeUp');
insert into interest (user_id, topic) values ( 3, 'tech');
insert into interest (user_id, topic) values ( 4, 'reading');
insert into interest (user_id, topic) values ( 5, 'art');
insert into interest (user_id, topic) values ( 6, 'tech');
insert into interest (user_id, topic) values ( 7, 'music');
insert into interest (user_id, topic) values ( 8, 'self improvement');
insert into interest (user_id, topic) values ( 9, 'science');
insert into interest (user_id, topic) values ( 10, 'series');
insert into interest (user_id, topic) values ( 11, 'movies');
insert into interest (user_id, topic) values ( 12, 'series');
insert into interest (user_id, topic) values ( 13, 'tech');
insert into interest (user_id, topic) values ( 14, 'food');
insert into interest (user_id, topic) values ( 15, 'science');
insert into interest (user_id, topic) values ( 16, 'self improvement');
insert into interest (user_id, topic) values ( 17, 'swimming');
insert into interest (user_id, topic) values ( 18, 'movies');
insert into interest (user_id, topic) values ( 19, 'swimming');
insert into interest (user_id, topic) values ( 20, 'e-games');
insert into interest (user_id, topic) values ( 21, 'swimming');
insert into interest (user_id, topic) values ( 22, 'movies');
insert into interest (user_id, topic) values ( 23, 'science');
insert into interest (user_id, topic) values ( 24, 'food');
insert into interest (user_id, topic) values ( 25, 'swimming');
insert into interest (user_id, topic) values ( 26, 'science');
insert into interest (user_id, topic) values ( 27, 'e-games');
insert into interest (user_id, topic) values ( 28, 'reading');
insert into interest (user_id, topic) values ( 29, 'art');
insert into interest (user_id, topic) values ( 30, 'movies');
insert into interest (user_id, topic) values ( 31, 'swimming');
insert into interest (user_id, topic) values ( 32, 'self improvement');
insert into interest (user_id, topic) values ( 33, 'movies');
insert into interest (user_id, topic) values ( 34, 'e-games');
insert into interest (user_id, topic) values ( 35, 'football');
insert into interest (user_id, topic) values ( 36, 'football');
insert into interest (user_id, topic) values ( 37, 'anime');
insert into interest (user_id, topic) values ( 38, 'swimming');
insert into interest (user_id, topic) values ( 39, 'music');
insert into interest (user_id, topic) values ( 40, 'movies');
insert into interest (user_id, topic) values ( 41, 'swimming');
insert into interest (user_id, topic) values ( 42, 'tech');
insert into interest (user_id, topic) values ( 43, 'series');
insert into interest (user_id, topic) values ( 44, 'food');
insert into interest (user_id, topic) values ( 45, 'football');
insert into interest (user_id, topic) values ( 46, 'e-games');
insert into interest (user_id, topic) values ( 47, 'self improvement');
insert into interest (user_id, topic) values ( 48, 'e-games');
insert into interest (user_id, topic) values ( 49, 'swimming');
insert into interest (user_id, topic) values ( 50, 'science');
